kind: ClusterConfig	
apiVersion: eksctl.io/v1alpha5
metadata:
  name: mktcluster
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    ssh: 
      publicKeyName: kp1
